# STRATIFIED OR DATABASE-WISE SPLIT
stratified: True

# INITIAL SETTINGS
data_dir: './data/physionet_preprocessed_smoke/'
save_dir: './data/split_csvs/'

#########################################
# FILENAMES
# -----------------
# A - CPSC
# Q - CPSC-Extra
# I - INCART
# S - PTB
# HR - PTB-XL
# E - Georgia
# JS - ChapmanShaoxing and Ningbo
#########################################
# DIRECTORIES USED FOR SPLIT
# --------------------------
# ChapmanShaoxing_Ningbo
# CPSC_CPSC-Extra
# G12EC
# INCART
# PTB_PTBXL
#########################################
# TRAIN: INCART, PTB and PTB-XL, Georgia, ChapmanShaoxing and Ningbo
# TEST: CPSC and CPSC-Extra

splits:
    - split_1:
      train: ['G12EC', 'INCART', 'PTB_PTBXL', 'ChapmanShaoxing_Ningbo']
      test: 'CPSC_CPSC-Extra'
    #- split_2:
    #  train: ['G12EC', 'INCART', 'PTB_PTBXL', 'CPSC_CPSC-Extra']
    #  test: 'ChapmanShaoxing_Ningbo'
    #- split_3:
    #  train: ['G12EC', 'INCART', 'CPSC_CPSC-Extra', 'ChapmanShaoxing_Ningbo']
    #  test: 'PTB_PTBXL'
    #- split_4:
    #  train: ['G12EC', 'PTB_PTBXL', 'CPSC_CPSC-Extra', 'ChapmanShaoxing_Ningbo']
    #  test: 'INCART'
    #- split_5:
    #  train: ['INCART', 'PTB_PTBXL', 'CPSC_CPSC-Extra', 'ChapmanShaoxing_Ningbo']
    #  test: 'G12EC'
