# INITIAL SETTINGS
train_file: INCART_G12EC_ChapmanShaoxing_Ningbo.csv
val_file: PTB_PTBXL.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0
epochs: 5
lr: 0.003000
weight_decay: 0.000010

# DEVICE CONFIGS
device_count: 1
