# INITIAL SETTINGS
train_file: CPSC_CPSC-Extra_G12EC_ChapmanShaoxing_Ningbo.csv
val_file: INCART.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0

# SAVE, LOAD AND DISPLAY INFORMATION
epochs: 1
