# INITIAL SETTINGS
train_file: INCART_CPSC_CPSC-Extra_ChapmanShaoxing_Ningbo.csv
val_file: PTB_PTBXL.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0

# SAVE, LOAD AND DISPLAY INFORMATION
epochs: 1
