# INITIAL SETTINGS
train_file: PTB_PTBXL_CPSC_CPSC-Extra_G12EC.csv
val_file: ChapmanShaoxing_Ningbo.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0

# SAVE, LOAD AND DISPLAY INFORMATION
epochs: 1
