# INITIAL SETTINGS
train_file: PTB_PTBXL_INCART_G12EC.csv
val_file: ChapmanShaoxing_Ningbo.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0
epochs: 5
lr: 0.003000
weight_decay: 0.000010

# DEVICE CONFIGS
device_count: 1
