# INITIAL SETTINGS
train_file: INCART_G12EC_ChapmanShaoxing_Ningbo.csv
val_file: CPSC_CPSC-Extra.csv

# TRAINING SETTINGS
batch_size: 64
num_workers: 0

# SAVE, LOAD AND DISPLAY INFORMATION
epochs: 50
